<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

	  <Company>PLDProjects</Company>
	  <Copyright>© 2026 PLDProjects</Copyright>
	  <Product>Financ.Application</Product>

	  <Version>3.3.0</Version>
	  <FileVersion>3.3.0.0</FileVersion>
	  <AssemblyVersion>1.0.0.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="CQRS\Contas\Querys\**" />
    <Compile Remove="DTOs\Contas\Get\**" />
    <EmbeddedResource Remove="CQRS\Contas\Querys\**" />
    <EmbeddedResource Remove="DTOs\Contas\Get\**" />
    <None Remove="CQRS\Contas\Querys\**" />
    <None Remove="DTOs\Contas\Get\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NetDevPack.SimpleMediator" Version="1.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Financ.Domain\Financ.Domain.csproj" />
  </ItemGroup>

</Project>
