<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

	  <Company>PLDProjects</Company>
	  <Copyright>© 2026 PLDProjects</Copyright>
	  <Product>Financ.Application</Product>

	  <Version>1.0.0</Version>
	  <FileVersion>1.0.0.0</FileVersion>
	  <AssemblyVersion>1.0.0.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NetDevPack.SimpleMediator" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Financ.Domain\Financ.Domain.csproj" />
  </ItemGroup>

</Project>
