services:
  financapi:
    build:
      context: .
      dockerfile: Financ.UI.Api/Dockerfile
    container_name: financ-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver
    networks:
      - financ-network

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: financ-sqlserver
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      # MSSQL_SA_PASSWORD deve ser mapeada explicitamente se o nome no .env for diferente
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD} 
    networks:
      - financ-network
    volumes:
      - sqlserver_data:/var/opt/mssql

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    # Removido 'network_mode: host' para permitir que ele veja a 'financapi' pelo nome do serviço
    networks:
      - financ-network
    env_file:
      - .env
    environment:
      # Mapeamento correto: a variável no .env chama-se CLOUDFLARED_TOKEN
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    depends_on:
      - financapi

networks:
  financ-network:
    driver: bridge

volumes:
  sqlserver_data:
