// <auto-generated />
using System;
using Financ.Infra.Data.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Financ.Infra.Data.Migrations
{
    [DbContext(typeof(AppContextoData))]
    [Migration("20260429002155_contaFavoritaDthr")]
    partial class contaFavoritaDthr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Financ.Domain.Entidades.ContasBancarias.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DthrReg")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("Decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoConta")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("fnc_contas", (string)null);
                });

            modelBuilder.Entity("Financ.Domain.Entidades.ContasBancarias.ContaUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Acesso")
                        .HasColumnType("int");

                    b.Property<bool>("ContaFavorita")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Dthr")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DthrReg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Expiracao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdConta")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdConta");

                    b.HasIndex("IdUsuario");

                    b.ToTable("fnc_contas_usuarios", (string)null);
                });

            modelBuilder.Entity("Financ.Domain.Entidades.ContasBancarias.Convite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Aceito")
                        .HasColumnType("bit");

                    b.Property<int>("Acesso")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expiracao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExpiracaoContaUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdConta")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioDestinatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdUsuarioRemetente")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdConta");

                    b.HasIndex("IdUsuarioDestinatario");

                    b.HasIndex("IdUsuarioRemetente");

                    b.ToTable("fnc_convites", (string)null);
                });

            modelBuilder.Entity("Financ.Domain.Entidades.Movimentações.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdConta")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdConta");

                    b.ToTable("fnc_categorias", (string)null);
                });

            modelBuilder.Entity("Financ.Domain.Entidades.Movimentações.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DthrConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DthrMovimentacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DthrReg")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdConta")
                        .HasColumnType("int");

                    b.Property<int>("IdFixo")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioCriador")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioExecutor")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdConta");

                    b.HasIndex("IdUsuarioCriador");

                    b.HasIndex("IdUsuarioExecutor");

                    b.ToTable("fnc_movimentacoes", (string)null);
                });

            modelBuilder.Entity("Financ.Domain.Entidades.Segurança.Autenticacao", b =>
                {
                    b.Property<string>("IdSession")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("ExpirationRefresh")
                        .HasColumnType("bigint");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Revoke")
                        .HasColumnType("bit");

                    b.HasKey("IdSession");

                    b.HasIndex("IdUsuario");

                    b.ToTable("fnc_autenticacao", (string)null);
                });

            modelBuilder.Entity("Financ.Domain.Entidades.Usuarios.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashPass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimeiroNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("fnc_usuarios", (string)null);
                });

            modelBuilder.Entity("Financ.Domain.Entidades.ContasBancarias.Conta", b =>
                {
                    b.OwnsOne("Financ.Domain.Objetos_de_Valor.Cor", "Cor", b1 =>
                        {
                            b1.Property<int>("ContaId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Cor");

                            b1.HasKey("ContaId");

                            b1.ToTable("fnc_contas");

                            b1.WithOwner()
                                .HasForeignKey("ContaId");
                        });

                    b.Navigation("Cor")
                        .IsRequired();
                });

            modelBuilder.Entity("Financ.Domain.Entidades.ContasBancarias.ContaUsuario", b =>
                {
                    b.HasOne("Financ.Domain.Entidades.ContasBancarias.Conta", "Conta")
                        .WithMany("ContaUsuarios")
                        .HasForeignKey("IdConta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Financ.Domain.Entidades.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Financ.Domain.Entidades.ContasBancarias.Convite", b =>
                {
                    b.HasOne("Financ.Domain.Entidades.ContasBancarias.Conta", "Conta")
                        .WithMany("Convites")
                        .HasForeignKey("IdConta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Financ.Domain.Entidades.Usuarios.Usuario", "Destinatario")
                        .WithMany()
                        .HasForeignKey("IdUsuarioDestinatario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Financ.Domain.Entidades.Usuarios.Usuario", "Remetente")
                        .WithMany()
                        .HasForeignKey("IdUsuarioRemetente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conta");

                    b.Navigation("Destinatario");

                    b.Navigation("Remetente");
                });

            modelBuilder.Entity("Financ.Domain.Entidades.Movimentações.Categoria", b =>
                {
                    b.HasOne("Financ.Domain.Entidades.ContasBancarias.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("IdConta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Financ.Domain.Objetos_de_Valor.Cor", "Cor", b1 =>
                        {
                            b1.Property<int>("CategoriaId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Cor");

                            b1.HasKey("CategoriaId");

                            b1.ToTable("fnc_categorias");

                            b1.WithOwner()
                                .HasForeignKey("CategoriaId");
                        });

                    b.Navigation("Conta");

                    b.Navigation("Cor")
                        .IsRequired();
                });

            modelBuilder.Entity("Financ.Domain.Entidades.Movimentações.Movimentacao", b =>
                {
                    b.HasOne("Financ.Domain.Entidades.Movimentações.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Financ.Domain.Entidades.ContasBancarias.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("IdConta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Financ.Domain.Entidades.ContasBancarias.ContaUsuario", "ContaUsuarioCriador")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCriador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Financ.Domain.Entidades.ContasBancarias.ContaUsuario", "ContaUsuarioExecutor")
                        .WithMany()
                        .HasForeignKey("IdUsuarioExecutor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categoria");

                    b.Navigation("Conta");

                    b.Navigation("ContaUsuarioCriador");

                    b.Navigation("ContaUsuarioExecutor");
                });

            modelBuilder.Entity("Financ.Domain.Entidades.Segurança.Autenticacao", b =>
                {
                    b.HasOne("Financ.Domain.Entidades.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Financ.Domain.Entidades.ContasBancarias.Conta", b =>
                {
                    b.Navigation("ContaUsuarios");

                    b.Navigation("Convites");
                });
#pragma warning restore 612, 618
        }
    }
}
