// <auto-generated />
using System;
using Financ.Infra.Data.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Financ.Infra.Data.Migrations
{
    [DbContext(typeof(AppContextoData))]
    partial class AppContextoDataModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Financ.Domain.Entidades.Autenticacao", b =>
                {
                    b.Property<string>("IdSession")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("ExpirationRefresh")
                        .HasColumnType("bigint");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Revoke")
                        .HasColumnType("bit");

                    b.HasKey("IdSession");

                    b.HasIndex("IdUsuario");

                    b.ToTable("fnc_autenticacao", (string)null);
                });

            modelBuilder.Entity("Financ.Domain.Entidades.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DthrReg")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoConta")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("fnc_contas", (string)null);
                });

            modelBuilder.Entity("Financ.Domain.Entidades.ContasUsuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Acesso")
                        .HasColumnType("int");

                    b.Property<DateTime>("DthrReg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Expiracao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdConta")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdConta");

                    b.HasIndex("IdUsuario");

                    b.ToTable("fnc_contas_usuarios", (string)null);
                });

            modelBuilder.Entity("Financ.Domain.Entidades.Convites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Aceito")
                        .HasColumnType("bit");

                    b.Property<int>("Acesso")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expiracao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExpiracaoContaUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdConta")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioDestinatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdUsuarioRemetente")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdConta");

                    b.HasIndex("IdUsuarioDestinatario");

                    b.HasIndex("IdUsuarioRemetente");

                    b.ToTable("fnc_convites", (string)null);
                });

            modelBuilder.Entity("Financ.Domain.Entidades.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashPass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimeiroNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("fnc_usuarios", (string)null);
                });

            modelBuilder.Entity("Financ.Domain.Entidades.Autenticacao", b =>
                {
                    b.HasOne("Financ.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Financ.Domain.Entidades.ContasUsuarios", b =>
                {
                    b.HasOne("Financ.Domain.Entidades.Conta", "Conta")
                        .WithMany("ContaUsuarios")
                        .HasForeignKey("IdConta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Financ.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Financ.Domain.Entidades.Convites", b =>
                {
                    b.HasOne("Financ.Domain.Entidades.Conta", "Conta")
                        .WithMany("Convites")
                        .HasForeignKey("IdConta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Financ.Domain.Entidades.Usuario", "Destinatario")
                        .WithMany()
                        .HasForeignKey("IdUsuarioDestinatario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Financ.Domain.Entidades.Usuario", "Remetente")
                        .WithMany()
                        .HasForeignKey("IdUsuarioRemetente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conta");

                    b.Navigation("Destinatario");

                    b.Navigation("Remetente");
                });

            modelBuilder.Entity("Financ.Domain.Entidades.Conta", b =>
                {
                    b.Navigation("ContaUsuarios");

                    b.Navigation("Convites");
                });
#pragma warning restore 612, 618
        }
    }
}
